import type { Metadata } from "next";
import localFont from "next/font/local";
import React from 'react';

import "./globals.css";
import { MainProvider } from "../context/contextAPI";

const geistSans = localFont({
  src: "../fonts/GeistVF.woff",
  variable: "--font-geist-sans",
  weight: "100 900",
});
const geistMono = localFont({
  src: "../fonts/GeistMonoVF.woff",
  variable: "--font-geist-mono",
  weight: "100 900",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <MainProvider>
      <html lang="pt-BR">
        <link rel="icon" href="/favicon.ico" />
        <title>CSkinstore</title>
        <body className={`${geistSans.variable} ${geistMono.variable}`}>
          {children}
        </body>
      </html>
    </MainProvider>
  );
}
